# Site settings
title: Tequilablob
email: tequilablob@gmail.com
description: "Gaming // Hardware // Benchmarks // Optimization"
# url: "http://tequilablob.com"



# Serve
port: 4000
host: 127.0.0.1
baseurl: "/tequilablob-web"

#compiling static site
sass:
    sass_dir: assets/css/_sass

#exclude from build into site folder
exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']
